name: Desplegar a Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Surge
      run: npm install --global surge

    - name: Desplegar a Surge
      run: |
        surge ./ --domain mi-pagina-web-john.surge.sh --token "${{ secrets.SURGE_TOKEN }}"
